version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# Enabling PDF and EPUB builds
# After this change, PDF and EPUB downloads will be available both from the “Downloads” section of the project home, as well as the flyout menu.
formats:
  - pdf
  - epub
